name: field_array_picker

version: 0.1.0

dependencies:
  uuid: 2.0.0
  intl: 0.15.8
  flutter_picker: 1.0.13
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: "2.5.0"